#!/usr/bin/env zsh

# install tmux plugin manager
if [ ! -d "$XDG_CONFIG_HOME/tmux/plugins" ]; then 
  git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm
fi

if [ ! -d "$ZDOTDIR" ]; then
  mkdir -p $ZDOTDIR
fi

if [ -f ~/.zshenv ]; then
  rm ~/.zshenv
fi

STOW_FOLDERS=(asdf git helix karabiner tmux zsh)

for folder in $STOW_FOLDERS
do 
  echo "stow $folder"
  stow -D $folder
  stow --dotfiles $folder
done

# install submodules
git submodule update --init --recursive

# specify iTerm directory
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles/iTerm/settings"

# enable custom directory
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

# save changes on exit
defaults write "com.googlecode.iterm2" "NoSyncNeverRemindPrefsChangesLostForFile_selection" '0'
