#!/usr/bin/env zsh

# install tmux plugin manager
if [ ! -d "$XDG_CONFIG_HOME/tmux/plugins" ]; then 
  git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm
fi

STOW_FOLDERS=(asdf git helix karabiner nvim tmux zshrc)

for folder in $STOW_FOLDERS
do 
  echo "stow $folder"
  stow -D $folder
  stow --dotfiles $folder
done

if [ "$1" = "nix" ]; then
  ln -sf $DOTFILES/zsh/zshrc.nix $ZDOTDIR/.zshrc 
else
  ln -sf $DOTFILES/zsh/zshrc.mac $ZDOTDIR/.zshrc
fi

# install submodules
git submodule update --init --recursive

# specify iTerm directory
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles/iTerm/settings"

# enable custom directory
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

# save changes on exit
defaults write "com.googlecode.iterm2" "NoSyncNeverRemindPrefsChangesLostForFile_selection" '0'
