#!/usr/bin/env bash

lazy() { NVIM_APPNAME="lazy" nvim; }

mkcd() {
  mkdir -p "$1"
  cd "$1"
}

cheat() {
    curl -s "cheat.sh/$1"
}

extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1     ;;
      *.tar.gz)    tar xzf $1     ;;
      *.bz2)       bunzip2 $1     ;;
      *.rar)       unrar e $1     ;;
      *.gz)        gunzip $1      ;;
      *.tar)       tar xf $1      ;;
      *.tbz2)      tar xjf $1     ;;
      *.tgz)       tar xzf $1     ;;
      *.zip)       unzip $1       ;;
      *.Z)         uncompress $1  ;;
      *.7z)        7z x $1        ;;
      *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
  else
      echo "'$1' is not a valid file"
  fi
}


# ::: SFDX :::

# open org
sfo() {
  if [[ -z "$1" ]]; then 
    sf alias list
  else
    sf org open -o $1;
  fi
}

# installs packages into one org based on another
# usage 'package [source org alias] [target org alias]'
dxcopypkg() {
  for OUTPUT in $(sfdx force:package:installed:list -u $1 --json | jq '.result [] .SubscriberPackageVersionId' -r)
  do
    sfdx force:package:install -u $2 -w 500 -p $OUTPUT -a package -r
  done
}
