#!/usr/bin/env bash

case "$OSTYPE" in
  darwin*)
    alias ls='gls'
  ;;
  linux*) 
  ;;
  *)
    # ...
  ;;
esac

# setting common options
alias vim='${VIM}'
alias ..="cd .."
alias cp='cp -iv'
alias mv='mv -iv'
alias rmdir='rmdir -v'
alias ln='ln -v'
alias grep='grep --color=auto'
alias ll='ls -alF --color=auto --human-readable --group-directories-first'
alias la='ls -A --color=auto --human-readable --group-directories-first'
alias l='ls -CF --color=auto --human-readable --group-directories-first'

# alias edit="code ~/.zshrc"
alias sc='source ${ZDOTDIR}/.zshrc'
alias myip="curl http://ipecho.net/plain; echo"

# ssh aliases
alias gwen="ssh josh@10.17.50.6"
alias gwenmnt="sshfs josh@10.17.50.6:/ ./mnt/gwen"

# caddy
alias caddyformat="docker exec -w /config caddy caddy fmt -overwrite"
alias caddyreload="docker exec -w /config caddy caddy reload"

# docker
alias dcup='docker compose -f /home/josh/docker/docker-compose.yml up -d' #brings up all containers if one is not defined after dcup
alias dcdown='docker compose -f /home/josh/docker/docker-compose.yml stop' #brings down all containers if one is not defined after dcdown
alias dcpull='docker compose -f /home/josh/docker/docker-compose.yml pull' #pulls all new images unless one is specified
alias dcr='docker compose -f /home/josh/docker/docker-compose.yml restart'
alias dclogs='docker compose -f /home/josh/docker/docker-compose.yml logs -tf --tail="50" '
alias dcps='docker compose -f /home/josh/docker/docker-compose.yml ps'
alias dclean='docker image prune -a --filter "until=24h"'

# SFDX
alias dxbu="sfdx force:data:bulk:upsert -s"
alias dxbd="sfdx force:data:bulk:delete -s"
alias soql="sfdx force:data:soql:query -q"
alias dxpull="sfdx force:source:pull"
alias dxpush="sfdx force:source:push"
alias dxs="sfdx force:source:status"
alias dxtrack="echo 'y' | sfdx force:source:tracking:clear && echo 'y' | sfdx force:source:tracking:reset"
alias dxdep="sfdx force:source:deploy"