#!/usr/bin/env bash

# general UNIX
alias ..="cd .."

alias ll='gls -alF --group-directories-first'
alias la='gls -A --group-directories-first'
alias l='gls -CF --group-directories-first'

alias plugpull="find ${ZDOTDIR:-$HOME}/.zsh_plugins -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull"

# alias edit="code ~/.zshrc"
alias sc="source ${ZDOTDIR}/.zshrc"
alias myip="curl http://ipecho.net/plain; echo"

# ssh aliases
alias gwen="ssh josh@192.168.1.6"
alias gwenmnt="sshfs josh@192.168.1.6:/ ./mnt/gwen"
# locations
alias res="cd $RESILIO_DIR"
alias gtd="cd $RESILIO_DIR/gtd"
alias inbox="cd $RESILIO_DIR/inbox"
alias proj="cd '$RESILIO_DIR/gtd/01 - Projects'"

# caddy
alias caddyformat="docker exec -w /config caddy caddy fmt -overwrite"
alias caddyreload="docker exec -w /config caddy caddy reload"

# docker
alias dcup='docker compose -f /home/josh/docker/docker-compose.yml up -d' #brings up all containers if one is not defined after dcup
alias dcdown='docker compose -f /home/josh/docker/docker-compose.yml stop' #brings down all containers if one is not defined after dcdown
alias dcpull='docker compose -f /home/josh/docker/docker-compose.yml pull' #pulls all new images unless one is specified
alias dcr='docker compose -f /home/josh/docker/docker-compose.yml restart'
alias dclogs='docker compose -f /home/josh/docker/docker-compose.yml logs -tf --tail="50" '
alias dcps='docker compose -f /home/josh/docker/docker-compose.yml ps'

# SFDX
alias dxbu="sfdx force:data:bulk:upsert -s"
alias dxbd="sfdx force:data:bulk:delete -s"
alias soql="sfdx force:data:soql:query -q"
alias dxpull="sfdx force:source:pull"
alias dxpush="sfdx force:source:push"
alias dxs="sfdx force:source:status"
alias dxtrack="echo 'y' | sfdx force:source:tracking:clear && echo 'y' | sfdx force:source:tracking:reset"
alias dxdep="sfdx force:source:deploy"