#!/usr/bin/env bash

setopt HIST_IGNORE_SPACE
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
HIST_STAMPS="yyyy-mm-dd"

export EDITOR="nvim"
export PATH=$DOTFILES/scripts:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/opt/homebrew/sbin:$PATH
export PATH=$PATH:$HOME/.docker/bin
export BUN_INSTALL="$HOME/.bun" 
export PATH="$BUN_INSTALL/bin:$PATH"

case "$OSTYPE" in
    darwin*)
    HOST_NAME=$(scutil --get HostName)
    export HOST_NAME
    
    export PATH="/opt/homebrew/bin:$PATH"
  ;;
  linux*)
    SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
  ;;
  *)
    # ...
  ;;
esac

export SFDX_DIR=$HOME/sfdx
export RESILIO_DIR="${HOME}/sync"

# home video project
export RAW_VIDEOS_DIR="${HOME}/home-video/videos-raw"
export PROCESSED_CLIPS_DIR="${HOME}/home-video/videos-processed"
export MEDIAGOBLIN_METADATA="${HOME}/home-video/mediagoblin-meta"
export SCENES_CSV="${MEDIAGOBLIN_METADATA}/scenes.csv"
export SCENES_YAML="${MEDIAGOBLIN_METADATA}/scenes.yaml"
export CSV_URL="https://docs.google.com/spreadsheets/d/1JKp6YT5-dIFD9aIqZhU1Tp-mi-trNCGGE97xakWXDUY/export?format=csv&id=1JKp6YT5-dIFD9aIqZhU1Tp-mi-trNCGGE97xakWXDUY&gid=401061703"
