#!/usr/bin/env zsh
#
# Cloned plugins are data, not config, so they live under XDG_DATA_HOME rather
# than in ZDOTDIR next to the files we actually track.

plugin_dir="${ZSH_DATA_DIR:-$HOME/.local/share/zsh}/plugins"

github_plugins=(
  marlonrichert/zsh-autocomplete
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions
  zsh-users/zsh-syntax-highlighting
  romkatv/powerlevel10k
)

for plugin in $github_plugins; do
  # clone the plugin from github if it doesn't exist
  if [[ ! -d $plugin_dir/$plugin ]]; then
    mkdir -p $plugin_dir/${plugin%/*}
    git clone --depth 1 --recursive https://github.com/$plugin.git $plugin_dir/$plugin
  fi
  # load the plugin
  for initscript in ${plugin#*/}.zsh ${plugin#*/}.zsh-theme ${plugin#*/}.plugin.zsh ${plugin#*/}.sh; do
    if [[ -f $plugin_dir/$plugin/$initscript ]]; then
      source $plugin_dir/$plugin/$initscript
      break
    fi
  done
done

# clean up
unset github_plugins
unset plugin
unset initscript
unset plugin_dir
