#!/usr/bin/env bash

export DOTFILES="$HOME/.dotfiles"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/local/share"
export XDG_CACHE_HOME="$HOME/cache"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"
export HISTFILE=$ZDOTDIR/.zhistory
export HISTSIZE=1000
export SAVEHIST=1000
export HIST_STAMPS="yyyy-mm-dd"

export PATH=$DOTFILES/scripts:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:$HOME/.docker/bin
export BUN_INSTALL="$HOME/.bun" 
export PATH="$BUN_INSTALL/bin:$PATH"

case "$OSTYPE" in
  darwin*)
    HOST_NAME=$(scutil --get HostName)
    export HOST_NAME
    export PATH="/opt/homebrew/bin:$PATH"
    export PATH=/opt/homebrew/sbin:$PATH
  ;;
  linux*)
    SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
    export PATH="$PATH:/opt/nvim-linux64/bin"
  ;;
  *)
    # ...
  ;;
esac
