#!/usr/bin/env bash

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export DOTFILES="$HOME/dotfiles"

. $DOTFILES/zsh/exports
. $DOTFILES/zsh/aliases
. $DOTFILES/zsh/named_dir
. $DOTFILES/zsh/functions
. $DOTFILES/zsh/plugins

## asdf
. $HOME/.asdf/asdf.sh
### set JAVA_HOME
. ~/.asdf/plugins/java/set-java-home.zsh

### append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
fpath=(${ZDOTDIR:-$HOME}/.zsh_plugins/zsh-users/zsh-completions/src $fpath)

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f $DOTFILES/zsh/p10k.zsh ]] || source $DOTFILES/zsh/p10k.zsh
